### ISSUE TITLE
Build process doesn't stop if an error is thrown

### ISSUE THREAD

**Issue by pathange-s** [codezri/buildzri#5]
If some build process throws any error in between, the process isn't stopped. It continues and gives error on build completion.

**Comment by shalithasuranga** [comment]
Hey @pathange-s, seems like this issue is already [fixed](https://github.com/codezri/buildzri/blob/ad30132df3e95992542b4ce9f11ce1caa35875d6/scripts/bz.py#L240) Thanks for reporting this :) Please re-open this if you notice a similar issue to this one
