### ISSUE TITLE
Building for macOS arm64 (Apple Silicon) is not possible

### ISSUE THREAD

**Issue by denisw** [codezri/buildzri#7]
Currently, it is not possible to build an `arm64` executable using BuildZri. The `get_arch()` function in `bz.py` automatically [chooses "x86_64" as target on Darwin](https://github.com/codezri/buildzri/blob/73b0ecadbfa62a0df87cf9b409c5d3ea96958d8f/scripts/bz.py#L23), even on Apple Silicon machines. A previous version of that script had a `use_mac_rosetta` option, but it was unused (always set to True) and removed in #2.

Editing `get_arch()` to return `'arm64'` seems to work just fine. So the only thing required would be some way to decide between a native and a Rosetta build when running `bz.py`.

**Comment by shalithasuranga** [comment]
Thanks for reporting the issue @denisw. Closing this as the latest script supports macOS cross-compilation (documentation needs to be updated)
